window.DungeonRushData = {
  heroCatalog: [
    { id: 'eldrin', name: 'Eldrin', className: 'Mago', race: 'Humano', hp: 25, maxHp: 25, ac: 10, initiative: 3, bonus: '+3', type: 'hero' },
    { id: 'nyssa', name: 'Nyssa', className: 'Ladina', race: 'Humana', hp: 25, maxHp: 25, ac: 10, initiative: 5, bonus: '+3', type: 'hero' },
    { id: 'brok', name: 'Brok', className: 'Bárbaro', race: 'Anão', hp: 30, maxHp: 30, ac: 12, initiative: 4, bonus: '+2', type: 'hero' },
    { id: 'theia', name: 'Theia', className: 'Clériga', race: 'Humana', hp: 25, maxHp: 25, ac: 10, initiative: 2, bonus: '+2', type: 'hero' },
    { id: 'kael-thyr', name: 'Kael’thyr', className: 'Arqueiro', race: 'Elfo Negro', hp: 25, maxHp: 25, ac: 10, initiative: 5, bonus: '+3', type: 'hero' },
    { id: 'atlas', name: 'Atlas', className: 'Cavaleiro', race: 'Humano', hp: 40, maxHp: 40, ac: 12, initiative: 2, bonus: '+2', type: 'hero' },
    { id: 'lysenda', name: 'Lysenda', className: 'Druida', race: 'Elfa Silvestre', hp: 30, maxHp: 30, ac: 10, initiative: 2, bonus: '+2', type: 'hero' },
    { id: 'lysara', name: 'Lysara', className: 'Feiticeira', race: 'Tritão', hp: 25, maxHp: 25, ac: 10, initiative: 3, bonus: '+2', type: 'hero' },
    { id: 'kai-tung', name: 'Kai Tung', className: 'Monge', race: 'Tabaxi', hp: 25, maxHp: 25, ac: 12, initiative: 5, bonus: '+3', type: 'hero' },
    { id: 'echo', name: 'Echo', className: 'Bardo', race: 'Kenku', hp: 25, maxHp: 25, ac: 10, initiative: 3, bonus: '+2', type: 'hero' },
    { id: 'thorgar', name: 'Thorgar', className: 'Paladino', race: 'Meio-Orc', hp: 35, maxHp: 35, ac: 12, initiative: 2, bonus: '+2', type: 'hero' },
    { id: 'morghena', name: 'Morghena', className: 'Bruxa', race: 'Tiefling', hp: 25, maxHp: 25, ac: 10, initiative: 3, bonus: '+2', type: 'hero' },
    { id: 'luthien', name: 'Luthien', className: 'Necromante', race: 'Elfa', hp: 25, maxHp: 25, ac: 10, initiative: 3, bonus: '+2', type: 'hero' },
    { id: 'cedric', name: 'Cedric', className: 'Guerreiro', race: 'Humano', hp: 30, maxHp: 30, ac: 10, initiative: 4, bonus: '+3', type: 'hero' },
  ],

  monsterCatalog: [
    {
      id: 'rato-gigante',
      name: 'Rato Gigante',
      hp: 10,
      maxHp: 10,
      ac: 9,
      initiative: 2,
      threat: 1,
      type: 'monster',
      damage: '1d4',
      ability: 'Enxame (Passiva): Se houver 2 ou mais monstros vivos na sala, o Rato Gigante ganha +1 de CA.',
    },
    {
      id: 'goblin',
      name: 'Goblin',
      hp: 12,
      maxHp: 12,
      ac: 10,
      initiative: 2,
      threat: 2,
      type: 'monster',
      damage: '1d4',
      ability: 'Tática Covarde: Ao ver outro monstro morrer, foge para a próxima sala.',
    },
    {
      id: 'esqueleto',
      name: 'Esqueleto',
      hp: 14,
      maxHp: 14,
      ac: 10,
      initiative: 1,
      threat: 2,
      type: 'monster',
      damage: '1d6',
      ability: 'Ossos estilhaçados: Ao morrer, causa 1 de dano ao jogador que o matou.',
    },
    {
      id: 'zumbi',
      name: 'Zumbi',
      hp: 20,
      maxHp: 20,
      ac: 10,
      initiative: 1,
      threat: 3,
      type: 'monster',
      damage: '1d6',
      ability: 'Tenaz: Primeira vez que cair a 0 PV, fica com 1 PV.',
    },
    {
      id: 'lobo-terrivel',
      name: 'Lobo Terrível',
      hp: 16,
      maxHp: 16,
      ac: 10,
      initiative: 3,
      threat: 3,
      type: 'monster',
      damage: '1d8',
      ability: 'Matilha (Passiva): Se houver mais de 2 monstros vivos na sala, o Lobo Terrível ganha +2 de dano.',
    },
    {
      id: 'orc',
      name: 'Orc',
      hp: 25,
      maxHp: 25,
      ac: 12,
      initiative: 1,
      threat: 4,
      type: 'monster',
      damage: '1d12',
      ability: 'Fúria Brutal: Quando estiver abaixo de metade do PV, recebe +2 de dano fixo nos ataques.',
    },
    {
      id: 'ogro',
      name: 'Ogro',
      hp: 35,
      maxHp: 35,
      ac: 10,
      initiative: 1,
      threat: 5,
      type: 'monster',
      damage: '1d12',
      ability: 'Golpe Demolidor: Acerto com 12+ no dado de ataque causa o status Atordoado ao alvo por 1 turno.',
    },
    {
      id: 'cavaleiro-negro',
      name: 'Cavaleiro Negro',
      hp: 20,
      maxHp: 20,
      ac: 12,
      initiative: 5,
      threat: 7,
      type: 'monster',
      damage: '2d6',
      ability: 'Guarda (Passiva): Enquanto vivo, todos os monstros ganham +1 de CA.',
    },
    {
      id: 'aber-racao-do-esgoto',
      name: 'Aberração do Esgoto',
      hp: 30,
      maxHp: 30,
      ac: 1,
      initiative: 1,
      threat: 5,
      type: 'monster',
      damage: '1d6',
      ability: 'Imundície: Sempre que acertar um ataque em um inimigo, causa o status Restrito por 1 turno.',
    },
    {
      id: 'cultista-sombrio',
      name: 'Cultista Sombrio',
      hp: 18,
      maxHp: 18,
      ac: 10,
      initiative: 4,
      threat: 7,
      type: 'monster',
      damage: '1d8',
      ability: 'Levante: Sempre que um monstro morrer no campo, invoque um esqueleto no lugar.',
    },
    {
      id: 'aranha-gigante',
      name: 'Aranha Gigante',
      hp: 14,
      maxHp: 14,
      ac: 10,
      initiative: 3,
      threat: 5,
      type: 'monster',
      damage: '1d10',
      ability: 'Vai teia: Sempre que acertar um ataque em um inimigo, causa o status Restrito por 1 turno.',
    },
    {
      id: 'gnoll-saqueador',
      name: 'Gnoll Saqueador',
      hp: 22,
      maxHp: 22,
      ac: 10,
      initiative: 2,
      threat: 5,
      type: 'monster',
      damage: '1d8',
      ability: 'Frenesi (Passiva): Se atacar um personagem que está abaixo da metade dos PV, cause +1d4 de dano.',
    },
    {
      id: 'sombra-errante',
      name: 'Sombra Errante',
      hp: 18,
      maxHp: 18,
      ac: 12,
      initiative: 3,
      threat: 4,
      type: 'monster',
      damage: '1d8',
      ability: 'No escuro: Sempre que acertar um ataque em um inimigo, causa o status Amedrontado por 1 turno.',
    },
    {
      id: 'demonio-menor',
      name: 'Demônio Menor',
      hp: 28,
      maxHp: 28,
      ac: 10,
      initiative: 3,
      threat: 6,
      type: 'monster',
      damage: '1d12',
      ability: 'Aura profana: Sempre que acertar um ataque em um inimigo, causa o status Amedrontado por 1 turno.',
    },
    {
      id: 'besta-deslocadora',
      name: 'Besta Deslocadora',
      hp: 20,
      maxHp: 20,
      ac: 12,
      initiative: 5,
      threat: 5,
      type: 'monster',
      damage: '1d10',
      ability: 'Deslocamento Ilusório: O primeiro ataque de cada inimigo contra o Deslocador recebe Desvantagem.',
    },
    {
      id: 'devorador-de-intelecto',
      name: 'Devorador de Intelecto',
      hp: 20,
      maxHp: 20,
      ac: 10,
      initiative: 3,
      threat: 4,
      type: 'monster',
      damage: '1d8',
      ability: 'Mente Exposta: Sempre que qualquer herói errar um ataque, ele sofre 1 de dano.',
    },
  ],

  rewardCatalog: [
    {
      id: 'pocao-cura',
      name: 'Poção de Cura',
      type: 'item',
      category: 'recompensa',
      effect: 'Cura em 2d8 PV todos os heróis desta sala.',
    },
    {
      id: 'pocao-mana',
      name: 'Poção de Mana',
      type: 'item',
      category: 'recompensa',
      effect: 'Durante esta sala, os heróis não possuem limite de uso das habilidades.',
    },
    {
      id: 'sorte-liquida',
      name: 'Sorte Líquida',
      type: 'item',
      category: 'recompensa',
      effect: 'Concede Inspiração a todos os jogadores durante esta sala.',
    },
    {
      id: 'forca-de-vontade',
      name: 'Força de Vontade',
      type: 'item',
      category: 'recompensa',
      effect: 'Heróis não podem ficar abaixo de 1 PV durante esta sala.',
    },
  ],

  bossCatalog: [
    {
      id: 'illithid',
      name: 'Illithid',
      type: 'boss',
      hp: 65,
      maxHp: 65,
      ac: 16,
      initiative: 5,
      bonus: '+3',
      threat: 20,
    },
    {
      id: 'beholder',
      name: 'Beholder',
      type: 'boss',
      hp: 60,
      maxHp: 60,
      ac: 14,
      initiative: 1,
      bonus: '+2',
      threat: 18,
    },
    {
      id: 'nightwalker',
      name: 'Nightwalker',
      type: 'boss',
      hp: 60,
      maxHp: 60,
      ac: 14,
      initiative: 3,
      bonus: '+2',
      threat: 18,
    },
    {
      id: 'balor',
      name: 'Balor',
      type: 'boss',
      hp: 70,
      maxHp: 70,
      ac: 15,
      initiative: 4,
      bonus: '+3',
      threat: 22,
    },
  ],

  defaultMockCombatants: [
    { id: 'nyssa', name: 'Nyssa', type: 'hero', hp: 18, maxHp: 25, ac: 11, initiative: 5, statuses: ['Inspiração', 'Atordoado'] },
    { id: 'goblin', name: 'Goblin', type: 'monster', hp: 8, maxHp: 15, ac: 8, initiative: 4, statuses: ['Restrito'] },
    { id: 'atlas', name: 'Atlas', type: 'hero', hp: 40, maxHp: 40, ac: 12, initiative: 2, statuses: [] },
    { id: 'theia', name: 'Theia', type: 'hero', hp: 21, maxHp: 25, ac: 10, initiative: 2, statuses: ['Amedrontado'] },
    { id: 'orc', name: 'Orc', type: 'monster', hp: 27, maxHp: 30, ac: 10, initiative: 2, statuses: [] },
    { id: 'zumbi', name: 'Zumbi', type: 'monster', hp: 20, maxHp: 20, ac: 8, initiative: 1, statuses: ['Atordoado'] },
  ],
};
